<div class="container polpri">
    <h1 class="titulo">Politicas de privacidad</h1>
    <p class="textos">Esta política de privacidad describe cómo se recopila, utiliza, almacena y divulga la información personal de los usuarios del launcher de juegos. Al utilizar el launcher de juegos, usted acepta esta política de privacidad.</p>
    <h4 class="subtitulos">Información personal recopilada</h4>
    <p class="textos">La información personal recopilada se utiliza para mejorar la experiencia de uso del launcher de juegos. La información personal se utiliza para los siguientes fines:</p>
    <ul class="listado">
        <li class="item_list">Nombre y apellidos</li>
        <li class="item_list">Dirección de correo electrónico</li>
        <li class="item_list">Nombre de usuario y contraseña</li>
        <li class="item_list">Información de contacto, incluidas direcciones de correo electrónico y números de teléfono</li>
        <li class="item_list">Información de pago, incluidos los detalles de la tarjeta de crédito</li>
        <li class="item_list">Información de uso del launcher de juegos, incluidos los juegos que se juegan y el tiempo dedicado a cada uno</li>
    </ul>
    <h4 class="subtitulos">Uso de la información personal</h4>
    <p class="textos">La información personal recopilada se utiliza para mejorar la experiencia de uso del launcher de juegos. La información personal se utiliza para los siguientes fines:</p>
    <ul class="listado">
        <li class="item_list">Procesamiento de pagos</li>
        <li class="item_list">Verificación de la identidad del usuario</li>
        <li class="item_list">Personalización de la experiencia de usuario</li>
        <li class="item_list">Análisis de uso del launcher de juegos</li>
        <li class="item_list">Comunicación con los usuarios</li>
    </ul>
    <h4 class="subtitulos">Divulgación de información personal</h4>
    <p class="textos">La información personal recopilada no se divulga a terceros, excepto en los siguientes casos:</p>
    <ul class="listado">
        <li class="item_list">Si se requiere por ley</li>
        <li class="item_list">Para cumplir con cualquier orden judicial o proceso legal</li>
        <li class="item_list">Para proteger los derechos, propiedad o seguridad del launcher de juegos o de sus usuarios</li>
        <li class="item_list">Si se vende el launcher de juegos o se fusiona con otra empresa, en cuyo caso la información personal recopilada se puede transferir a la nueva empresa propietaria</li>
    </ul>
    <h4 class="subtitulos">Seguridad de la información personal</h4>
    <p class="textos">El launcher de juegos toma medidas razonables para garantizar la seguridad de la información personal recopilada. Sin embargo, no se puede garantizar la seguridad de la información personal transmitida a través de Internet. El usuario asume el riesgo de la transmisión de información personal a través de Internet.</p>
    <h4 class="subtitulos">Chat y foros</h4>
    <p class="textos">El launcher de juegos puede ofrecer características que permitan a los usuarios interactuar entre sí, como chat y foros. Estos canales de comunicación son una gran manera para que los usuarios puedan compartir sus experiencias de juego, hacer preguntas y obtener respuestas de otros jugadores, y crear comunidades en línea. Sin embargo, los usuarios deben tener en cuenta que son responsables de cualquier información que publiquen en estos canales. Esto incluye, pero no se limita a, mensajes, imágenes, videos, comentarios y enlaces. Es importante recordar que una vez que se publica la información en estos canales, puede ser vista por otros usuarios y no se puede eliminar completamente.</p>
    <p class="textos">El launcher de juegos no es responsable de la información que los usuarios publiquen en estos canales. Si bien hacemos todo lo posible para monitorear y moderar estos canales, no podemos garantizar que toda la información publicada sea precisa, oportuna o apropiada. Por lo tanto, es responsabilidad del usuario evaluar y verificar la información publicada por otros usuarios antes de confiar en ella. Además, el launcher de juegos se reserva el derecho de eliminar cualquier información que consideremos inapropiada, ofensiva o que viole nuestros términos y condiciones de uso.</p>
    <p class="textos"> Le recordamos que cualquier información que publique en estos canales de comunicación será considerada como no confidencial y de dominio público. Por lo tanto, no debe compartir información personal o confidencial en estos canales, incluidos, entre otros, su nombre completo, dirección de correo electrónico, dirección física o número de teléfono. Si decide compartir información personal en estos canales, lo hace bajo su propio riesgo y el launcher de juegos no será responsable de ningún uso no autorizado de dicha información.</p>
    <h4 class="subtitulos">Cookies y tecnologías de seguimiento</h4>
    <p class="textos">El launcher de juegos utiliza cookies y otras tecnologías de seguimiento para mejorar la experiencia de uso del launcher de juegos. Las cookies son pequeños archivos que se colocan en su computadora para almacenar información sobre sus preferencias de navegación. Las cookies se pueden utilizar para personalizar la experiencia del usuario y mejorar la funcionalidad del launcher de juegos.</p>
    <h4 class="subtitulos">Retención de cuenta</h4>
    <p class="textos">Se retendrá la cuenta si usted infringe nuestros términos y condiciones para el uso de nuestro software, en la cantidad de tiempo requerida por su tipo de sanción. Sus datos quedarán seguros en nuestro sistema a no ser que usted desee eliminar su cuenta.</p>
    <h4 class="subtitulos">Recuperación de cuenta</h4>
    <p class="textos">Por algún caso particular, usted podrá recuperar su cuenta en los próximos 30 días comunicándose con nuestro equipo al joyboxteam@gmail.com, pasado este periodo sus datos se eliminarán del sistema y no será posible recuperar su cuenta.</p>
    <h4 class="subtitulos">Productos de terceros</h4>
    <p class="textos">Nuestro sitio web y launcher proporcionan anuncios adecuados a las preferencias del usuario, de otras marcas que no tendrán acceso a ningún dato de los usuarios ya que para nuestra empresa no le es comerciable.</p>
    <h4 class="subtitulos">Modificaciones de la política de privacidad</h4>
    <p class="textos">El launcher de juegos se reserva el derecho de modificar esta política de privacidad en cualquier momento. Las modificaciones se harán efectivas inmediatamente después de la publicación de la política de privacidad modificada en el sitio web del launcher de juegos. Se recomienda a los usuarios que revisen periódicamente la política de privacidad para mantenerse informados sobre cualquier cambio.</p>
    <h4 class="subtitulos">Contacto</h4>
    <p class="textos">Si tiene alguna pregunta o inquietud sobre esta política de privacidad, comuníquese con nosotros a través de la sección de contacto del sitio web del launcher de juegos. Es importante para nosotros mantener una comunicación abierta con nuestros usuarios, por lo que estaremos encantados de escuchar cualquier sugerencia o preocupación que pueda tener sobre nuestra política de privacidad. Ya sea que tenga preguntas sobre cómo se recopila y utiliza su información personal, o sobre cómo protegemos su privacidad, no dude en ponerse en contacto con nosotros. Nuestro equipo de atención al cliente está disponible para responder a sus preguntas y ayudarlo en todo lo que necesite. Sabemos lo importante que es la privacidad para nuestros usuarios, por lo que nos tomamos muy en serio cualquier inquietud relacionada con este tema. No dude en contactarnos si necesita cualquier tipo de aclaración o información adicional. Estamos comprometidos a garantizar la transparencia y la claridad en nuestra política de privacidad y a trabajar en conjunto con nuestros usuarios para garantizar su satisfacción y confianza en nuestro servicio. Recuerde que puede ponerse en contacto con nosotros en cualquier momento a través de la sección de contacto del sitio web del launcher de juegos. Esperamos poder atenderle pronto y brindarle toda la información que necesita.</p>
</div>